#!/bin/bash

set -eu

error() {
    echo "$@" >&2
}

usage() {
    readonly usage_message=$(cat <<EOF
Usage: $0 NAME
Setup a directory for new slide.
EOF
             )
    error "${usage_message}"
    exit 1
}

if (($# != 1)); then
    error "specified $# arguments: expected 1"
    usage
fi
readonly current_dir=$(pwd -P)
readonly template_dir=$(dirname "$(readlink -f "$0")")
readonly src_dir="${template_dir}/template"
readonly dst_dir="${current_dir}/$1"
mkdir -p "${dst_dir}"
cp -irv "${src_dir}"/* "${dst_dir}"
